"""Database configuration and models"""

from sqlalchemy.ext.asyncio import create_async_engine, AsyncSession
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import sessionmaker
from datetime import datetime, date
from sqlalchemy import Column, String, Integer, Float, DateTime, Date, Text, ForeignKey, CheckConstraint, JSON, Boolean
from sqlalchemy.orm import relationship
from sqlalchemy.dialects.postgresql import UUID, JSONB
import uuid

from src.config import settings

# Create async engine
engine = create_async_engine(
    settings.database_url,
    echo=settings.log_level == "DEBUG",
    future=True,
)

# Create async engine for company database (for centralized audit_logs)
company_engine = create_async_engine(
    settings.COMPANY_DATABASE_URL,
    echo=False,  # Don't echo SQL for audit log writes
    future=True,
)

# Create session factory
async_session_maker = sessionmaker(
    engine, class_=AsyncSession, expire_on_commit=False
)

# Create session factory for company database (for audit logs)
company_async_session_maker = sessionmaker(
    company_engine, class_=AsyncSession, expire_on_commit=False
)

# Base class for models
Base = declarative_base()


# Database Models
class Trip(Base):
    """Trip model"""
    __tablename__ = "trips"

    # ID will be generated by service in TRIP-DDMMYYYY-{sequence} format
    id = Column(String(50), primary_key=True)
    user_id = Column(String(50), nullable=False)
    company_id = Column(String(50), nullable=False)
    branch = Column(String(100), nullable=False)  # Contains branch ID (UUID)
    truck_plate = Column(String(20), nullable=False)
    truck_model = Column(String(100), nullable=False)
    truck_capacity = Column(Integer, nullable=False)
    driver_id = Column(String(50), nullable=False)
    driver_name = Column(String(100), nullable=False)
    driver_phone = Column(String(20), nullable=False)
    status = Column(
        String(50),
        CheckConstraint("status IN ('planning', 'loading', 'on-route', 'paused', 'completed', 'cancelled', 'truck-malfunction')", name="check_trip_status"),
        nullable=False,
        default="planning"
    )
    origin = Column(String(100))
    destination = Column(String(100))
    distance = Column(Integer)
    estimated_duration = Column(Integer)
    pre_trip_time = Column(Integer, default=30)
    post_trip_time = Column(Integer, default=15)
    capacity_used = Column(Integer, default=0)
    capacity_total = Column(Integer, nullable=False)
    trip_date = Column(Date, nullable=False)

    # Maintenance/pause tracking
    maintenance_note = Column(Text, nullable=True)
    paused_at = Column(DateTime, nullable=True)
    paused_reason = Column(String(500), nullable=True)
    resumed_at = Column(DateTime, nullable=True)

    created_at = Column(DateTime, default=datetime.utcnow)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)

    # Relationships
    orders = relationship("TripOrder", back_populates="trip", cascade="all, delete-orphan")
    routes = relationship("TripRoute", back_populates="trip", cascade="all, delete-orphan")
    # audit_logs relationship removed due to complex foreign key structure


class TripOrder(Base):
    """Trip Order model"""
    __tablename__ = "trip_orders"

    id = Column(Integer, primary_key=True, index=True)
    trip_id = Column(String(50), ForeignKey("trips.id", ondelete="CASCADE"), nullable=False)
    user_id = Column(String(50), nullable=False)
    company_id = Column(String(50), nullable=False)
    order_id = Column(String(50), nullable=False)
    customer = Column(String(200), nullable=False)
    customer_address = Column(Text)
    status = Column(
        String(50),
        CheckConstraint("status IN ('assigned', 'loading', 'on-route', 'completed')", name="check_trip_order_status"),
        nullable=False,
        default="assigned"
    )
    tms_order_status = Column(
        String(50),
        CheckConstraint("tms_order_status IN ('available', 'partial', 'fully_assigned')", name="check_tms_order_status"),
        default="available"
    )
    item_status = Column(
        String(50),
        CheckConstraint("item_status IN ('pending_to_assign', 'planning', 'loading', 'on_route', 'delivered', 'failed', 'returned')", name="check_item_status"),
        default="pending_to_assign"
    )
    total = Column(Float, nullable=False)
    weight = Column(Float, nullable=False)  # Changed from Integer to Float for decimal weights
    volume = Column(Float, nullable=False)  # Changed from Integer to Float for decimal volumes
    items = Column(Integer, nullable=False)
    priority = Column(
        String(20),
        CheckConstraint("priority IN ('high', 'medium', 'low', 'normal')", name="check_priority"),
        nullable=False
    )
    delivery_status = Column(
        String(50),
        CheckConstraint("delivery_status IN ('pending', 'out-for-delivery', 'delivered', 'failed', 'returned')", name="check_delivery_status"),
        default="pending"
    )
    address = Column(Text)
    sequence_number = Column(Integer, nullable=False, default=0)  # Delivery sequence for drag & drop ordering
    assigned_at = Column(DateTime, default=datetime.utcnow)
    original_order_id = Column(String(50))  # For split orders
    original_items = Column(Integer)        # For split orders
    original_weight = Column(Float)         # For split orders (changed from Integer to Float)
    items_json = Column(JSON)              # Store assigned items with quantities
    remaining_items_json = Column(JSON)    # Store remaining items for partial assignments

    # Additional order details
    customer_contact = Column(String(200))
    customer_phone = Column(String(50))
    product_name = Column(String(200))
    quantity = Column(Integer, default=1)
    special_instructions = Column(Text)
    delivery_instructions = Column(Text)

    # Relationships
    trip = relationship("Trip", back_populates="orders")


class TripRoute(Base):
    """Trip Route model"""
    __tablename__ = "trip_routes"

    id = Column(Integer, primary_key=True, index=True)
    trip_id = Column(String(50), ForeignKey("trips.id", ondelete="CASCADE"), nullable=False)
    user_id = Column(String(50), nullable=False)
    company_id = Column(String(50), nullable=False)
    sequence_number = Column(Integer, nullable=False)
    order_id = Column(Integer, ForeignKey("trip_orders.id"))
    location = Column(String(200), nullable=False)
    estimated_arrival = Column(DateTime)
    status = Column(
        String(20),
        CheckConstraint("status IN ('pending', 'in-progress', 'completed')", name="check_route_status"),
        default="pending"
    )
    created_at = Column(DateTime, default=datetime.utcnow)

    # Relationships
    trip = relationship("Trip", back_populates="routes")


class TMSAuditLog(Base):
    """TMS Audit Log model (deprecated - use CompanyAuditLog instead)"""
    __tablename__ = "tms_audit_logs"

    id = Column(Integer, primary_key=True, index=True)
    user_id = Column(String(50), nullable=False)
    company_id = Column(String(50), nullable=False)
    action = Column(String(100), nullable=False)
    module = Column(String(50), nullable=False, default="TMS")
    record_id = Column(String(50))
    record_type = Column(String(50))  # 'trip' or 'trip_order'
    details = Column(Text)
    timestamp = Column(DateTime, default=datetime.utcnow)

    # Relationships
    # Note: This relationship is complex due to the generic audit log structure
    # and can be added later when needed for specific audit log queries


class CompanyAuditLog(Base):
    """Centralized Audit Log model from company_db"""
    __tablename__ = "audit_logs"

    id = Column(UUID(as_uuid=True), primary_key=True)
    tenant_id = Column(String(255))
    user_id = Column(String(255))
    user_name = Column(String(255))
    user_role = Column(String(100))
    user_email = Column(String(255))
    entity_type = Column(String(50))
    entity_id = Column(String(255))
    entity_name = Column(String(500))
    action = Column(String(100))
    module = Column(String(50))
    sub_module = Column(String(50))
    old_status = Column(String(50))
    new_status = Column(String(50))
    status_changed = Column(Boolean)
    description = Column(Text)
    reason = Column(Text)
    notes = Column(Text)
    meta_data = Column(JSONB)
    ip_address = Column(String(45))
    user_agent = Column(Text)
    request_id = Column(String(100))
    action_timestamp = Column(DateTime(timezone=True))
    created_at = Column(DateTime(timezone=True))
    updated_at = Column(DateTime(timezone=True))
    old_values = Column(JSONB)
    new_values = Column(JSONB)
    from_status = Column(String(50))
    to_status = Column(String(50))
    approval_status = Column(String(20))
    service_name = Column(String(50))


# Dependency to get database session
async def get_db():
    """Dependency to get database session (matching company service pattern)"""
    async with async_session_maker() as session:
        try:
            yield session
        except Exception:
            await session.rollback()
            raise


async def get_async_session() -> AsyncSession:
    """Get async database session"""
    async with async_session_maker() as session:
        try:
            yield session
        finally:
            await session.close()


async def get_company_db_session() -> AsyncSession:
    """Get async session for company database (for centralized audit_logs)"""
    async with company_async_session_maker() as session:
        try:
            yield session
        finally:
            await session.close()


async def write_audit_log_to_company(
    entity_id: str,
    entity_type: str,
    module: str,
    action: str,
    from_status: str = None,
    to_status: str = None,
    description: str = None,
    user_id: str = None,
    user_name: str = None,
    user_email: str = None,
    user_role: str = None,
    tenant_id: str = None,
):
    """
    Write audit log to centralized audit_logs table in company_db

    Args:
        entity_id: ID of the entity (trip_id, order_id, etc.)
        entity_type: Type of entity ('trip', 'trip_order', etc.)
        module: Module name ('trips', 'orders', etc.)
        action: Action performed ('create', 'status_change', etc.)
        from_status: Previous status (for status changes)
        to_status: New status (for status changes)
        description: Human-readable description
        user_id: ID of the user who performed the action
        user_name: Name of the user
        user_email: Email of the user
        user_role: Role of the user
        tenant_id: Tenant ID
    """
    from sqlalchemy import text

    async with company_async_session_maker() as session:
        query = text("""
            INSERT INTO audit_logs (
                tenant_id, user_id, user_name, user_email, user_role,
                action, module, entity_type, entity_id,
                description, from_status, to_status, created_at
            ) VALUES (
                :tenant_id, :user_id, :user_name, :user_email, :user_role,
                :action, :module, :entity_type, :entity_id,
                :description, :from_status, :to_status, NOW()
            )
        """)

        await session.execute(query, {
            "tenant_id": tenant_id or "",
            "user_id": user_id or "",
            "user_name": user_name,
            "user_email": user_email,
            "user_role": user_role,
            "action": action,
            "module": module,
            "entity_type": entity_type,
            "entity_id": entity_id,
            "description": description or f"{action} {entity_type} {entity_id}",
            "from_status": from_status,
            "to_status": to_status
        })
        await session.commit()