"""
Security module for Company Service
"""

from .auth import TokenData, verify_token, extract_token_from_header
from .dependencies import (
    get_current_token_data,
    get_current_tenant_id,
    get_current_user_id,
    require_permissions,
    require_any_permission,
    require_tenant_access,
    require_self_or_permission,
    require_role,
    is_active_user,
    # Permission groups
    BRANCH_READ_ALL,
    BRANCH_READ,
    BRANCH_CREATE,
    BRANCH_UPDATE,
    BRANCH_DELETE,
    BRANCH_MANAGE_ALL,
    BRANCH_MANAGE_OWN,
    CUSTOMER_READ_ALL,
    CUSTOMER_READ,
    CUSTOMER_CREATE,
    CUSTOMER_UPDATE,
    CUSTOMER_DELETE,
    # User management permissions
    USER_READ_ALL,
    USER_READ,
    USER_READ_OWN,
    USER_CREATE,
    USER_UPDATE,
    USER_UPDATE_OWN,
    USER_DELETE,
    USER_MANAGE_ALL,
    USER_INVITE,
    USER_ACTIVATE,
    # Role management permissions
    ROLE_READ,
    ROLE_CREATE,
    ROLE_UPDATE,
    ROLE_DELETE,
    ROLE_ASSIGN,
    # Profile management permissions
    PROFILE_READ,
    PROFILE_READ_OWN,
    PROFILE_CREATE,
    PROFILE_UPDATE,
    PROFILE_UPDATE_OWN,
    PROFILE_DELETE,
    PROFILE_UPLOAD_AVATAR,
    # Vehicle permissions
    VEHICLE_READ_ALL,
    VEHICLE_READ,
    VEHICLE_CREATE,
    VEHICLE_UPDATE,
    VEHICLE_DELETE,
    VEHICLE_ASSIGN,
    # Driver permissions
    DRIVER_READ_ALL,
    DRIVER_READ,
    DRIVER_UPDATE,
    # Generic resource permissions
    RESOURCES_READ,
    RESOURCES_READ_ALL,
    # Product permissions
    PRODUCT_READ_ALL,
    PRODUCT_READ,
    PRODUCT_CREATE,
    PRODUCT_UPDATE,
    PRODUCT_DELETE,
    PRODUCT_STOCK_ADJUST,
    # Report permissions
    COMPANY_REPORTS_READ,
    COMPANY_REPORTS_EXPORT,
)
from .permissions import (
    Permission,
    PERMISSION_GROUPS,
    ROLE_PERMISSIONS,
    PermissionChecker,
    get_readable_permissions,
    validate_permissions,
    BRANCH_PERMISSIONS,
    CUSTOMER_PERMISSIONS,
    VEHICLE_PERMISSIONS,
    PRODUCT_PERMISSIONS,
    REPORT_PERMISSIONS,
)
from .exceptions import (
    SecurityException,
    AuthenticationError,
    AuthorizationError,
    TokenExpiredError,
    TokenInvalidError,
    PermissionDeniedError,
    TenantAccessError,
    RateLimitExceededError,
    AccountLockedException,
    security_exception_handler,
    http_exception_handler,
    validation_exception_handler,
    general_exception_handler,
    log_security_event,
    log_authentication_event,
)

__all__ = [
    # Auth
    "TokenData",
    "verify_token",
    "extract_token_from_header",

    # Dependencies
    "get_current_token_data",
    "get_current_tenant_id",
    "get_current_user_id",
    "require_permissions",
    "require_any_permission",
    "require_tenant_access",
    "require_self_or_permission",
    "require_role",
    "is_active_user",

    # Permission groups
    "BRANCH_READ_ALL",
    "BRANCH_READ",
    "BRANCH_CREATE",
    "BRANCH_UPDATE",
    "BRANCH_DELETE",
    "BRANCH_MANAGE_ALL",
    "BRANCH_MANAGE_OWN",
    "CUSTOMER_READ_ALL",
    "CUSTOMER_READ",
    "CUSTOMER_CREATE",
    "CUSTOMER_UPDATE",
    "CUSTOMER_DELETE",
    # User management permissions
    "USER_READ_ALL",
    "USER_READ",
    "USER_READ_OWN",
    "USER_CREATE",
    "USER_UPDATE",
    "USER_UPDATE_OWN",
    "USER_DELETE",
    "USER_MANAGE_ALL",
    "USER_INVITE",
    "USER_ACTIVATE",
    # Role management permissions
    "ROLE_READ",
    "ROLE_CREATE",
    "ROLE_UPDATE",
    "ROLE_DELETE",
    "ROLE_ASSIGN",
    # Profile management permissions
    "PROFILE_READ",
    "PROFILE_READ_OWN",
    "PROFILE_CREATE",
    "PROFILE_UPDATE",
    "PROFILE_UPDATE_OWN",
    "PROFILE_DELETE",
    "PROFILE_UPLOAD_AVATAR",
    # Vehicle permissions
    "VEHICLE_READ_ALL",
    "VEHICLE_READ",
    "VEHICLE_CREATE",
    "VEHICLE_UPDATE",
    "VEHICLE_DELETE",
    "VEHICLE_ASSIGN",
    # Driver permissions
    "DRIVER_READ_ALL",
    "DRIVER_READ",
    "DRIVER_UPDATE",
    # Generic resource permissions
    "RESOURCES_READ",
    "RESOURCES_READ_ALL",
    # Product permissions
    "PRODUCT_READ_ALL",
    "PRODUCT_READ",
    "PRODUCT_CREATE",
    "PRODUCT_UPDATE",
    "PRODUCT_DELETE",
    "PRODUCT_STOCK_ADJUST",
    # Report permissions
    "COMPANY_REPORTS_READ",
    "COMPANY_REPORTS_EXPORT",

    # Permissions
    "Permission",
    "PERMISSION_GROUPS",
    "ROLE_PERMISSIONS",
    "PermissionChecker",
    "get_readable_permissions",
    "validate_permissions",
    "BRANCH_PERMISSIONS",
    "CUSTOMER_PERMISSIONS",
    "VEHICLE_PERMISSIONS",
    "PRODUCT_PERMISSIONS",
    "REPORT_PERMISSIONS",

    # Exceptions
    "SecurityException",
    "AuthenticationError",
    "AuthorizationError",
    "TokenExpiredError",
    "TokenInvalidError",
    "PermissionDeniedError",
    "TenantAccessError",
    "RateLimitExceededError",
    "AccountLockedException",
    "security_exception_handler",
    "http_exception_handler",
    "validation_exception_handler",
    "general_exception_handler",
    "log_security_event",
    "log_authentication_event",
]